services:
  db:
    image: mongo:latest
    container_name: unahur_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - unahur_mongodata:/data/db
redis:
    image: redis:alpine
    container_name: unahur_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  unahur_mongodata: